3rd attempt with toolchain. Created it on websited and copied it back to repo

diff --git a/.bluemix/catalog-pipeline.yml b/.bluemix/catalog-pipeline.yml
--- a/.bluemix/catalog-pipeline.yml
+++ b/.bluemix/catalog-pipeline.yml
@@ -2,7 +2,7 @@
 stages:
 - name: Build
   inputs:
-  - url: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory.git
+  - url: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory-fabio.git
     type: git
     branch: integration
     dir_name: null
@@ -13,79 +13,44 @@ stages:
     target:
       region_id: ibm:yp:us-south
       organization: cent@us.ibm.com
-      space: cloudnative-integration
-    COMMAND: |+
-      #!/bin/bash
-      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.  
-      log_and_echo "$LABEL" "Starting build script"
-
-      export JAVA_HOME=~/java8
-
-      cd catalog; ./gradlew build docker
-      cd ..
-      pwd
-
-      cp -r catalog/docker/* .
-
-      find .
-
-      # The IBM Container BM Containers plug-in (cf ic), Git client (git), and IDS Inventory CLI (ids-inv) have been installed.
-      # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix 
-      #####################
-      # Run unit tests    #
-      #####################
-      log_and_echo "$LABEL" "No unit tests cases have been checked in"
-
-      SPACE=$($IC_COMMAND info|grep 'Bluemix Space'|awk '{print $NF}'|sed "s/\(.*\)\((.*\)/\1/")
-      IMAGE_NAME=$(echo $IMAGE_NAME|sed "s/-$SPACE//")
-      REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
-      FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${SPACE}
-
-      ######################################
-      # Build Container via Dockerfile     #
-      ######################################
-
-      # REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
-      # FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}
-      # If you wish to receive slack notifications, set SLACK_WEBHOOK_PATH as a property on the stage.
-
-      if [ -f Dockerfile ]; then 
-          log_and_echo "$LABEL" "Building ${FULL_REPOSITORY_NAME}"
-          ${EXT_DIR}/utilities/sendMessage.sh -l info -m "New container build requested for ${FULL_REPOSITORY_NAME}"
-          # build image
-          BUILD_COMMAND=""
-          if [ "${USE_CACHED_LAYERS}" == "true" ]; then 
-              BUILD_COMMAND="build --pull --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
-              ice_retry ${BUILD_COMMAND}
-              RESULT=$?
-          else 
-              BUILD_COMMAND="build --no-cache --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
-              ice_retry ${BUILD_COMMAND}
-              RESULT=$?
-          fi 
-
-          if [ $RESULT -ne 0 ]; then
-              log_and_echo "$ERROR" "Error building image"
-              ice_retry info 
-              ice_retry images
-              ${EXT_DIR}/print_help.sh
-              ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Container build of ${FULL_REPOSITORY_NAME} failed. $(get_error_info)"
-              exit 1
-          else
-              log_and_echo "$SUCCESSFUL" "Container build of ${FULL_REPOSITORY_NAME} was successful"
-              ${EXT_DIR}/utilities/sendMessage.sh -l good -m "Container build of ${FULL_REPOSITORY_NAME} was successful"
-          fi  
-      else 
-          log_and_echo "$ERROR" "Dockerfile not found in project"
-          ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Failed to get Dockerfile. $(get_error_info)"
-          exit 1
-      fi  
-
-      ######################################################################################
-      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
-      ######################################################################################
-      echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
-    IMAGE_NAME: us-micro-catalog-cloudnative-integration
+      space: fabio-case
+    COMMAND: "#!/bin/bash\n# The following colors have been defined to help with presentation\
+      \ of logs: green, red, label_color, no_color.  \nlog_and_echo \"$LABEL\" \"\
+      Starting build script\"\n\nexport JAVA_HOME=~/java8\n\ncd catalog; ./gradlew\
+      \ build docker\ncd ..\npwd\n\ncp -r catalog/docker/* .\n\nfind .\n\n# The IBM\
+      \ Container BM Containers plug-in (cf ic), Git client (git), and IDS Inventory\
+      \ CLI (ids-inv) have been installed.\n# Based on the organization and space\
+      \ selected in the Job credentials are in place for both IBM Container Service\
+      \ and IBM Bluemix \n#####################\n# Run unit tests    #\n#####################\n\
+      log_and_echo \"$LABEL\" \"No unit tests cases have been checked in\"\n\nSPACE=$($IC_COMMAND\
+      \ info|grep 'Bluemix Space'|awk '{print $NF}'|sed \"s/\\(.*\\)\\((.*\\)/\\1/\"\
+      )\nIMAGE_NAME=$(echo $IMAGE_NAME|sed \"s/-$SPACE//\")\nREGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}\n\
+      FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${SPACE}\n\n######################################\n\
+      # Build Container via Dockerfile     #\n######################################\n\
+      \n# REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}\n# FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}\n\
+      # If you wish to receive slack notifications, set SLACK_WEBHOOK_PATH as a property\
+      \ on the stage.\n\nif [ -f Dockerfile ]; then \n    log_and_echo \"$LABEL\"\
+      \ \"Building ${FULL_REPOSITORY_NAME}\"\n    ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l info -m \"New container build requested for ${FULL_REPOSITORY_NAME}\"\n\
+      \    # build image\n    BUILD_COMMAND=\"\"\n    if [ \"${USE_CACHED_LAYERS}\"\
+      \ == \"true\" ]; then \n        BUILD_COMMAND=\"build --pull --tag ${FULL_REPOSITORY_NAME}\
+      \ ${WORKSPACE}\"\n        ice_retry ${BUILD_COMMAND}\n        RESULT=$?\n  \
+      \  else \n        BUILD_COMMAND=\"build --no-cache --tag ${FULL_REPOSITORY_NAME}\
+      \ ${WORKSPACE}\"\n        ice_retry ${BUILD_COMMAND}\n        RESULT=$?\n  \
+      \  fi \n\n    if [ $RESULT -ne 0 ]; then\n        log_and_echo \"$ERROR\" \"\
+      Error building image\"\n        ice_retry info \n        ice_retry images\n\
+      \        ${EXT_DIR}/print_help.sh\n        ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l bad -m \"Container build of ${FULL_REPOSITORY_NAME} failed. $(get_error_info)\"\
+      \n        exit 1\n    else\n        log_and_echo \"$SUCCESSFUL\" \"Container\
+      \ build of ${FULL_REPOSITORY_NAME} was successful\"\n        ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l good -m \"Container build of ${FULL_REPOSITORY_NAME} was successful\"\n\
+      \    fi  \nelse \n    log_and_echo \"$ERROR\" \"Dockerfile not found in project\"\
+      \n    ${EXT_DIR}/utilities/sendMessage.sh -l bad -m \"Failed to get Dockerfile.\
+      \ $(get_error_info)\"\n    exit 1\nfi  \n\n######################################################################################\n\
+      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE\
+      \    #\n######################################################################################\n\
+      echo \"IMAGE_NAME=${FULL_REPOSITORY_NAME}\" >> $ARCHIVE_DIR/build.properties"
+    IMAGE_NAME: us-micro-catalog-cloudnative-fabio
     USE_CACHED_LAYERS: 'true'
 - name: Deploy
   inputs:
@@ -133,8 +98,8 @@ stages:
     target:
       region_id: ibm:yp:us-south
       organization: cent@us.ibm.com
-      space: cloudnative-integration
-    COMMAND: |+
+      space: fabio-case
+    COMMAND: |-
       #!/bin/sh
 
       set +e
@@ -158,7 +123,6 @@ stages:
       git_retry clone https://github.com/ssibm/deployscripts.git deployscripts
 
       OPTIONAL_ARGS="${OPTIONAL_ARGS} \
-            -e server.port=${PORT} \
             -e eureka.client.fetchRegistry=true \
             -e eureka.client.registerWithEureka=true \
             -e "eureka.client.serviceUrl.defaultZone=${EUREKA_REGISTRY_URL}" \
@@ -208,9 +172,9 @@ stages:
           exit $RESULT
       fi
       echo -e "${green}Execution complete${no_label}"
-    OPTIONAL_ARGS: -m ${MEMORY}
+    OPTIONAL_ARGS: -m "${MEMORY}"
     PORT: '8081'
-    CONTAINER_NAME: us-micro-catalog-cloudnative-integration
+    CONTAINER_NAME: us-micro-catalog-cloudnative-fabio
     DEPLOY_TYPE: red_black
 hooks:
 - enabled: true
